specVersion: 1.0.0
name: kusama-transfers
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your SubQuery
  project
repository: 'https://github.com/RaekwonIII/kusama-transfers'
schema:
  file: ./schema.graphql
network:
  chainId: '0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe'
  endpoint: 'wss://kusama-rpc.polkadot.io'
  dictionary: 'https://api.subquery.network/sq/subquery/kusama-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
